import { Vehicle } from './types';

export const vehicles: Vehicle[] = [
  {
    id: '1',
    model: 'Camry',
    year: 2024,
    trim: 'LE',
    price: 26520,
    msrp: 26520,
    image: '/images/camry.jpg',
    fuelType: 'Gasoline',
    drivetrain: 'FWD',
    engine: '2.5L 4-Cylinder',
    horsepower: 203,
    mpg: { city: 28, highway: 39 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'LED Headlights'],
    description: 'The reliable and efficient Camry LE offers exceptional value with advanced safety features.',
    category: 'Sedan',
  },
  {
    id: '2',
    model: 'Camry',
    year: 2024,
    trim: 'XLE Hybrid',
    price: 32500,
    msrp: 32500,
    image: '/images/camry-hybrid.jpg',
    fuelType: 'Hybrid',
    drivetrain: 'FWD',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: 208,
    mpg: { city: 51, highway: 53 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'Premium Audio', 'Leather Seats'],
    description: 'Premium hybrid efficiency with luxury features and outstanding fuel economy.',
    category: 'Sedan',
  },
  {
    id: '3',
    model: 'RAV4',
    year: 2024,
    trim: 'XLE',
    price: 31225,
    msrp: 31225,
    image: '/images/rav4.jpg',
    fuelType: 'Gasoline',
    drivetrain: 'AWD',
    engine: '2.5L 4-Cylinder',
    horsepower: 203,
    mpg: { city: 27, highway: 35 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'All-Wheel Drive', 'Power Liftgate'],
    description: 'Versatile compact SUV with all-wheel drive capability and modern technology.',
    category: 'SUV',
  },
  {
    id: '4',
    model: 'RAV4',
    year: 2024,
    trim: 'XSE Hybrid',
    price: 37680,
    msrp: 37680,
    image: '/images/rav4-hybrid.jpg',
    fuelType: 'Hybrid',
    drivetrain: 'AWD',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: 219,
    mpg: { city: 41, highway: 38 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'Sport-Tuned Suspension', 'Premium Audio'],
    description: 'Sporty hybrid SUV with exceptional fuel economy and all-wheel drive.',
    category: 'SUV',
  },
  {
    id: '5',
    model: 'Highlander',
    year: 2024,
    trim: 'XLE',
    price: 41520,
    msrp: 41520,
    image: '/images/highlander.jpg',
    fuelType: 'Gasoline',
    drivetrain: 'AWD',
    engine: '3.5L V6',
    horsepower: 295,
    mpg: { city: 21, highway: 29 },
    seating: 7,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'Third-Row Seating', 'Panoramic Moonroof'],
    description: 'Spacious midsize SUV perfect for families with three-row seating.',
    category: 'SUV',
  },
  {
    id: '6',
    model: 'Corolla',
    year: 2024,
    trim: 'LE',
    price: 22100,
    msrp: 22100,
    image: '/images/corolla.jpg',
    fuelType: 'Gasoline',
    drivetrain: 'FWD',
    engine: '2.0L 4-Cylinder',
    horsepower: 169,
    mpg: { city: 32, highway: 41 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 3.0', 'LED Headlights'],
    description: 'Affordable and efficient compact sedan with advanced safety technology.',
    category: 'Sedan',
  },
  {
    id: '7',
    model: 'Corolla',
    year: 2024,
    trim: 'LE Hybrid',
    price: 23450,
    msrp: 23450,
    image: '/images/corolla-hybrid.jpg',
    fuelType: 'Hybrid',
    drivetrain: 'FWD',
    engine: '1.8L 4-Cylinder Hybrid',
    horsepower: 138,
    mpg: { city: 53, highway: 46 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 3.0', 'Hybrid System'],
    description: 'Ultra-efficient hybrid with best-in-class fuel economy.',
    category: 'Sedan',
  },
  {
    id: '8',
    model: 'Tacoma',
    year: 2024,
    trim: 'TRD Off-Road',
    price: 38200,
    msrp: 38200,
    image: '/images/tacoma.jpg',
    fuelType: 'Gasoline',
    drivetrain: '4WD',
    engine: '3.5L V6',
    horsepower: 278,
    mpg: { city: 18, highway: 22 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense', 'Off-Road Package', 'Crawl Control'],
    description: 'Rugged midsize truck built for adventure with advanced off-road capabilities.',
    category: 'Truck',
  },
  {
    id: '9',
    model: 'Tundra',
    year: 2024,
    trim: 'SR5',
    price: 38965,
    msrp: 38965,
    image: '/images/tundra.jpg',
    fuelType: 'Gasoline',
    drivetrain: '4WD',
    engine: '3.5L Twin-Turbo V6',
    horsepower: 389,
    mpg: { city: 18, highway: 24 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'Towing Package', '12-inch Touchscreen'],
    description: 'Powerful full-size truck with impressive towing capacity and modern tech.',
    category: 'Truck',
  },
  {
    id: '10',
    model: 'Prius',
    year: 2024,
    trim: 'LE',
    price: 27565,
    msrp: 27565,
    image: '/images/prius.jpg',
    fuelType: 'Hybrid',
    drivetrain: 'FWD',
    engine: '2.0L 4-Cylinder Hybrid',
    horsepower: 194,
    mpg: { city: 57, highway: 56 },
    seating: 5,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 3.0', 'Wireless Charging', 'Digital Key'],
    description: 'Iconic hybrid with revolutionary design and exceptional efficiency.',
    category: 'Sedan',
  },
  {
    id: '11',
    model: 'Sienna',
    year: 2024,
    trim: 'XLE',
    price: 40400,
    msrp: 40400,
    image: '/images/sienna.jpg',
    fuelType: 'Hybrid',
    drivetrain: 'FWD',
    engine: '2.5L 4-Cylinder Hybrid',
    horsepower: 245,
    mpg: { city: 36, highway: 36 },
    seating: 8,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense 2.5+', 'Sliding Doors', 'Tri-Zone Climate'],
    description: 'Family-friendly minivan with hybrid efficiency and versatile seating.',
    category: 'Van',
  },
  {
    id: '12',
    model: '4Runner',
    year: 2024,
    trim: 'TRD Off-Road',
    price: 42000,
    msrp: 42000,
    image: '/images/4runner.jpg',
    fuelType: 'Gasoline',
    drivetrain: '4WD',
    engine: '4.0L V6',
    horsepower: 270,
    mpg: { city: 17, highway: 20 },
    seating: 7,
    features: ['Apple CarPlay', 'Android Auto', 'Toyota Safety Sense', 'Off-Road Package', 'KDSS Suspension'],
    description: 'Legendary off-road SUV with body-on-frame construction and serious capability.',
    category: 'SUV',
  },
];

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find(v => v.id === id);
}

export function filterVehicles(filters: {
  minPrice?: number;
  maxPrice?: number;
  fuelType?: Vehicle['fuelType'];
  drivetrain?: Vehicle['drivetrain'];
  category?: Vehicle['category'];
  minMpg?: number;
  searchQuery?: string;
}): Vehicle[] {
  return vehicles.filter(vehicle => {
    if (filters.minPrice && vehicle.price < filters.minPrice) return false;
    if (filters.maxPrice && vehicle.price > filters.maxPrice) return false;
    if (filters.fuelType && vehicle.fuelType !== filters.fuelType) return false;
    if (filters.drivetrain && vehicle.drivetrain !== filters.drivetrain) return false;
    if (filters.category && vehicle.category !== filters.category) return false;
    if (filters.minMpg && vehicle.mpg.highway < filters.minMpg) return false;
    
    if (filters.searchQuery) {
      const query = filters.searchQuery.toLowerCase();
      const searchableText = `${vehicle.model} ${vehicle.trim} ${vehicle.year} ${vehicle.category}`.toLowerCase();
      if (!searchableText.includes(query)) return false;
    }
    
    return true;
  });
}

